- lambda:
    name: randomflicker
    update_interval: 200 ms
    lambda: |-
      auto call = id(${devicename}_rgb).turn_on();
      float r = random_float() * 2.0f - 1.0f;
      r =  r * r * r;
      call.set_transition_length(r);
      static double br=id(global_brightness);
      call.set_brightness(br + r/10);
      call.set_publish(false);
      call.set_save(false);
      call.perform();
- lambda:
    name: Chill Mode
    update_interval: 70s
    lambda: |-
      auto call = id(${devicename}_rgb).turn_on();
      call.set_transition_length(55000);
      //call.set_white(0.0);
      light::ESPColor c = light::ESPColor::random_color();
      call.set_rgb((c.red%255)/255.0, (c.green%255)/255.0, (c.blue%255)/255.0);
      call.set_publish(false);
      call.set_save(false);
      call.perform();
- lambda:
    name: Chill Mode (Vibrant)
    update_interval: 120s
    lambda: |-
      auto call = id(${devicename}_rgb).turn_on();
      call.set_transition_length(80000);
      //call.set_white(0.0);
      light::ESPColor c = light::ESPColor::random_color();
      call.set_rgb((c.red%128)/255.0, (c.green%128)/255.0, (c.blue%128)/255.0);
      call.set_publish(false);
      call.set_save(false);
      call.perform();
- lambda:
    name: Disco
    update_interval: 500ms
    lambda: |-
      auto call = id(${devicename}_rgb).turn_on();
      //call.set_transition_length(rand() % 400 + 1);
      call.set_transition_length(500);
      //call.set_white(0.0);
      light::ESPColor c = light::ESPColor::random_color();
      call.set_rgb((c.red)/255.0, (c.green)/255.0, (c.blue)/255.0);
      call.set_publish(false);
      call.set_save(false);
      call.perform();
- lambda:
    name: WTF
    update_interval: 200ms
    lambda: |-
      auto call = id(${devicename}_rgb).turn_on();
      call.set_transition_length(200);
      //call.set_white(0.0);
      call.set_brightness((rand() % 255 + 1) / 255.0);
      call.set_color_temperature(rand() % 2 == 0 ? 0: 512);
      call.perform();
- strobe:
    name: Lightning
    colors:
      - state: True
        brightness: 100%
        red: 90%
        green: 90%
        blue: 100%
        duration: 50ms
      - state: False
        duration: 50ms
      - state: True
        brightness: 100%
        red: 90%
        green: 90%
        blue: 100%
        duration: 160ms
      - state: False
        duration: 50ms
      - state: True
        brightness: 100%
        red: 90%
        green: 90%
        blue: 100%
        duration: 50ms
      - state: False
        duration: 3000ms
- flicker:
    name: Candle
- lambda:
    name: Plasma
    update_interval: 50s
    lambda: |-
      static int state = 0;
      auto call = id(${devicename}_rgb).turn_on();
      // Transtion of 1000ms = 1s
      call.set_transition_length(55000);
      if (state == 0) {
        call.set_rgb(255, 0, 126);
      } else if (state == 1) {
        call.set_rgb(68,188,253);
      } else if (state == 2) {
        call.set_rgb(0,255,129);
      } else {
        call.set_rgb(254,223,164);
      }
      call.perform();
      state += 1;
      if (state == 4)
        state = 0;