  - platform: esp8266_pwm
    id: output_green
    pin: GPIO4
    max_power: 100%
    frequency: ${frequency_rgb}
  - platform: esp8266_pwm
    id: output_red
    pin: GPIO12
    max_power: 100%
    frequency: ${frequency_rgb}
  - platform: esp8266_pwm
    id: output_blue
    pin: GPIO14
    max_power: 100%
    frequency: ${frequency_rgb}
  - platform: esp8266_pwm
    id: output_white
    pin: GPIO5
    max_power: 80%
    frequency: ${frequency_w}
