substitutions:
  devicename: switchlavalamp
  friendly_name: Schalter
  room: Lavalampe
  update_interval_long: 10min
  update_interval_short: 2s
  icon: mdi:power-standby
esphome:
  esp8266_restore_from_flash: true
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout # https://github.com/arendst/Tasmota/blob/66d9ff14ac804ea6f63fe6e2f371357a138d3bba/README.md#attention-all-versions
logger:
wifi: !include shared/wifi.yaml
web_server: !include shared/webserver.yaml
time: !include shared/time.yaml
text_sensor: !include shared/textsensors.yaml
sensor: !include shared/sensors.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
output:
  - platform: gpio
    pin: GPIO12
    id: ${devicename}_relay
  - platform: esp8266_pwm
    id: ${devicename}_light
    pin: GPIO13
    inverted: true
light:
  - platform: binary
    name: ${friendly_name} (${room}) Light
    id: ${devicename}
    output: ${devicename}_relay
  - platform: monochromatic
    internal: true
    name: ${friendly_name} (${room}) LED
    output: ${devicename}_light
    id: ${devicename}_led
switch:
  - platform: gpio
    pin: GPIO12
    id: relay
  - platform: restart
    name: ${friendly_name} (${room}) Restart
  - platform: template
    name: ${friendly_name} (${room}) Relay
    optimistic: true
    id: ${devicename}_button
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: ${devicename}_led
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: ${devicename}_led
binary_sensor:
  - platform: gpio
    internal: true
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: button
    on_press:
      - switch.toggle: ${devicename}_button
  - platform: status
    name: ${friendly_name} (${room}) Status
