substitutions:
  devicename: switchwhz
  friendly_name: Schalter 1
  room: Wohnzimmer
  update_interval_short: 2min
  update_interval_long: 10min
  icon: mdi:gesture-tap-box
esphome:
  esp8266_restore_from_flash: true
  name: ${devicename}
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout # https://github.com/arendst/Tasmota/blob/66d9ff14ac804ea6f63fe6e2f371357a138d3bba/README.md#attention-all-versions
logger:
wifi: !include shared/wifi.yaml
web_server: !include shared/webserver.yaml
time: !include shared/time.yaml
text_sensor: !include shared/textsensors.yaml
sensor: !include shared/sensors.yaml
api: !include shared/api.yaml
ota: !include shared/ota.yaml
output:
  - platform: gpio
    pin: GPIO12
    id: ${devicename}_relay
  - platform: esp8266_pwm
    id: ${devicename}_light
    pin: GPIO13
    inverted: true
light:
  - platform: binary
    name: ${friendly_name} (${room}) Light
    id: ${devicename}
    output: ${devicename}_relay
  - platform: monochromatic
    internal: true
    name: ${friendly_name} (${room}) LED
    output: ${devicename}_light
    id: ${devicename}_led
switch:
  - platform: gpio
    pin: GPIO12
    id: relay
  - platform: restart
    name: ${friendly_name} (${room}) Restart
  - platform: template
    name: ${friendly_name} (${room}) Relay
    optimistic: true
    restore_state: true
    id: ${devicename}_button
    turn_on_action:
      - switch.turn_on: relay
      - light.turn_on: ${devicename}_led
      - homeassistant.service:
         service: light.turn_on
         data:
            entity_id: light.mood_lights_cwww
      - homeassistant.service:
          service: scene.create
          data:
            scene_id: wohnzimmer_on_the_fly
            snapshot_entities: 'light.mood_lights_rgb'
      - homeassistant.service:
          service: light.turn_off
          data:
            entity_id: light.mood_lights_rgb
    turn_off_action:
      - switch.turn_off: relay
      - light.turn_off: ${devicename}_led
      - homeassistant.service:
          service: light.turn_off
          data:
            entity_id: light.mood_lights_cwww
      - homeassistant.service:
          service: scene.turn_on
          data:
            entity_id: scene.wohnzimmer_on_the_fly
            transition: '3'
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: button
    on_press:
      - switch.toggle: ${devicename}_button
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: ${devicename}_binbutton
    on_click:
      - min_length: 1ms
        max_length: 350ms
        then:
          - switch.toggle: ${devicename}_button
      - min_length: 500ms
        max_length: 5000ms
        then:
          - homeassistant.service:
              service: scene.turn_on
              data:
                entity_id: scene.chill_mode_on
          - homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.mood_lights_rgb
          - homeassistant.service:
              service: light.turn_on
              data:
                entity_id: light.schalter_lavalampe_light
          - homeassistant.service:
              service: light.turn_off
              data:
                entity_id: light.mood_lights_cwww
      - min_length: 5000ms
        max_length: 7000ms
        then:
          - homeassistant.service:
              service: light.turn_off
              data:
                entity_id: light.all_lights
  - platform: status
    name: ${friendly_name} (${room}) Status
